#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=13
ENV_FILE=".env.demo"

banner "Becca — hackathon demo deploy (Render free tier, \$0)"

# ── Stage 1 ────────────────────────────────────────────────────────────────
stage "Preflight — fixed values, secrets, service names"
say "Everything this wizard collects lands in .env.demo. At the Render stages"
say "you paste that file straight into Render's env editor — with ONE per-"
say "service extra (INLINE_WORKER) the wizard calls out when you get there."
if ! grep -q '^\.env\.demo$' .gitignore 2>/dev/null; then
  printf '.env.demo\n' >> .gitignore
  say "added .env.demo to .gitignore (it will hold real secrets)"
fi
SESSION_SECRET_VALUE=$(openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')
DEMO_CODE_VALUE=$(_existing DEMO_ACCESS_CODE || openssl rand -hex 8 2>/dev/null || head -c 8 /dev/urandom | od -An -tx1 | tr -d ' \n')
write_env ENVIRONMENT "production"
write_env SESSION_SECRET "$SESSION_SECRET_VALUE"
write_env DEMO_ACCESS_CODE "$DEMO_CODE_VALUE"
note "ENVIRONMENT=production is what lets visitors dial THEIR OWN phones:"
note "outside production the gateway refuses any number not on DIAL_ALLOWLIST."
ask DEMO_USER_EMAIL "Demo account email (needn't be a real mailbox) [demo@becca.live]:"
DEMO_USER_EMAIL=${DEMO_USER_EMAIL:-demo@becca.live}
write_env DEMO_USER_EMAIL "$DEMO_USER_EMAIL"
say ""
say "Pick your two Render service names now — they become the hostnames."
ask APP_SERVICE "App (visitor) service name [becca-demo-app]:"
APP_SERVICE=${APP_SERVICE:-becca-demo-app}
ask CONSOLE_SERVICE "Console service name [becca-demo-console]:"
CONSOLE_SERVICE=${CONSOLE_SERVICE:-becca-demo-console}
write_env APP_SERVICE "$APP_SERVICE"
write_env CONSOLE_SERVICE "$CONSOLE_SERVICE"
write_env CLIENT_HOST "${APP_SERVICE}.onrender.com"
write_env CONSOLE_HOST "${CONSOLE_SERVICE}.onrender.com"
write_env COOKIE_DOMAIN ""
note "COOKIE_DOMAIN is deliberately EMPTY: onrender.com is on the browsers'"
note "Public Suffix List, so cookies cannot span the two services. Sessions"
note "are host-only — which is why the QR code must use the app host."
write_env PUBLIC_WEBHOOK_BASE "https://${APP_SERVICE}.onrender.com"
note "Webhooks target the app service — it's the one we keep awake, and the"
note "one that settles test-call billing when Telnyx reports the call ended."
write_env TELNYX_MODE "real"
write_env MAX_CALL_MINUTES "5"
note "MAX_CALL_MINUTES=5 caps every call and shrinks the per-call wallet hold"
note "to \$1.50 at the default \$0.30/min — more concurrent visitors per \$."
write_env DIAL_ALLOWLIST ""
write_env ASSISTANT_CONVERSATION_MODEL "anthropic/claude-haiku-4-5"
write_env ASSISTANT_VOICE "Telnyx.Ultra.81d6df1d-6175-4f24-9641-76d14b6d67cc"
write_env PYTHON_VERSION "3.14.0"
note "Python 3.14 is mandatory — the code uses 3.14-only syntax (PEP 758)."

# ── Stage 2 ────────────────────────────────────────────────────────────────
stage "Telnyx — API key, public key, the shared number"
say "All visitor test calls dial out from ONE number on your Telnyx account."
warn "This must be a PAID Telnyx account — trial accounts can only dial"
warn "verified numbers, which is exactly what the demo can't live with."
open_url "https://portal.telnyx.com/#/app/api-keys"
step "Create an API key named 'becca-demo' and copy it."
ask_secret TELNYX_API_KEY "Paste the Telnyx API key:"
write_env TELNYX_API_KEY "$TELNYX_API_KEY"
step "From Account Settings -> Keys & Credentials, copy the account PUBLIC key"
step "(verifies webhook signatures — it is not secret)."
ask TELNYX_PUBLIC_KEY "Paste the Telnyx public key:"
write_env TELNYX_PUBLIC_KEY "$TELNYX_PUBLIC_KEY"
DEV_FROM=$(grep -E '^TELNYX_FROM_NUMBER=' .env 2>/dev/null | cut -d= -f2- || true)
[[ -n "$DEV_FROM" ]] && say "dev from-number: $DEV_FROM"
ask TELNYX_FROM_NUMBER "The shared caller-ID number, E.164 (e.g. +234...):"
write_env TELNYX_FROM_NUMBER "$TELNYX_FROM_NUMBER"

# ── Stage 3 ────────────────────────────────────────────────────────────────
stage "Anthropic — API key (agent generation)"
say "'Describe' builds each agent with Claude. Without a key the app falls"
say "back to a canned fake generator: every agent identical — demo-killing."
open_url "https://console.anthropic.com/settings/keys"
step "Create a key named 'becca-demo' and copy it."
ask_secret ANTHROPIC_API_KEY "Paste the Anthropic API key:"
write_env ANTHROPIC_API_KEY "$ANTHROPIC_API_KEY"

# ── Stage 4 ────────────────────────────────────────────────────────────────
stage "Google OAuth — optional, console/staff only"
say "Visitors NEVER touch Google — the QR route bypasses it. Google sign-in"
say "only gates the staff console (wallet refills, watching test calls)."
say "Skippable: the seed script can also refill the wallet from your laptop."
if confirm "Set up Google OAuth for the console?"; then
  open_url "https://console.cloud.google.com/apis/credentials"
  step "Create credentials -> OAuth client ID -> 'Web application',"
  step "name 'becca-demo'. Under 'Authorized redirect URIs' add exactly:"
  say  "    https://${CONSOLE_SERVICE}.onrender.com/auth/callback"
  step "Create, then copy the Client ID and Client secret."
  ask GOOGLE_CLIENT_ID "Paste the Client ID:"
  ask_secret GOOGLE_CLIENT_SECRET "Paste the Client secret:"
  write_env GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
  write_env GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"
  ask BECCA_STAFF_EMAILS "Comma-separated staff Google emails:"
  write_env BECCA_STAFF_EMAILS "$BECCA_STAFF_EMAILS"
  note "Keep this list tight during the demo — anyone on it becomes full"
  note "staff (all accounts) on their first sign-in."
else
  write_env GOOGLE_CLIENT_ID ""
  write_env GOOGLE_CLIENT_SECRET ""
  write_env BECCA_STAFF_EMAILS ""
  note "Skipped. The console will refuse all sign-ins; wallet refills happen"
  note "by re-running the seed script (stage 9 shows the command)."
fi

# ── Stage 5 ────────────────────────────────────────────────────────────────
stage "Render — FREE managed Postgres"
warn "Free Render databases EXPIRE 30 days after creation (then a 14-day"
warn "grace before deletion). Create it now, close to demo day — and put a"
warn "calendar reminder to pg_dump anything you care about before expiry."
open_url "https://dashboard.render.com/new/database"
step "Name: becca-demo-db · pick any region (remember it — the web services"
step "must use the SAME region) · Instance type: FREE."
step "Create, wait until it's 'Available', then from the database page copy"
step "BOTH connection strings:"
say  "    'Internal Database URL'  (the services use this)"
say  "    'External Database URL'  (your laptop uses this to migrate + seed)"
ask RAW_INTERNAL_URL "Paste the Internal Database URL:"
ask_secret RAW_EXTERNAL_URL "Paste the External Database URL:"
DATABASE_URL_VALUE="${RAW_INTERNAL_URL/postgresql:\/\//postgresql+asyncpg:\/\/}"
DATABASE_URL_VALUE="${DATABASE_URL_VALUE/postgres:\/\//postgresql+asyncpg:\/\/}"
EXTERNAL_URL_VALUE="${RAW_EXTERNAL_URL/postgresql:\/\//postgresql+asyncpg:\/\/}"
EXTERNAL_URL_VALUE="${EXTERNAL_URL_VALUE/postgres:\/\//postgresql+asyncpg:\/\/}"
write_env DATABASE_URL "$DATABASE_URL_VALUE"
write_env EXTERNAL_DATABASE_URL "$EXTERNAL_URL_VALUE"
note "both schemes rewritten to postgresql+asyncpg:// — the app's driver."
ask RENDER_REGION "Which region did you pick? (so later stages remind you):"
write_env RENDER_REGION "$RENDER_REGION"

# ── Stage 6 ────────────────────────────────────────────────────────────────
stage "Migrate the database — from this machine"
say "Render's FREE tier has no pre-deploy command, so migrations run from"
say "here, over the External URL. (The app service also re-runs them on"
say "every boot, so future deploys stay migrated.)"
if confirm "Run 'uv run alembic upgrade head' against the new database now?"; then
  if DATABASE_URL="$EXTERNAL_URL_VALUE" uv run alembic upgrade head; then
    say "migrations applied."
  else
    warn "migration failed — check the External URL and rerun this wizard."
    SKIPPED+=("alembic upgrade head against the demo database")
  fi
else
  SKIPPED+=("alembic upgrade head against the demo database")
fi

# ── Stage 7 ────────────────────────────────────────────────────────────────
stage "Render — the APP web service (visitors, webhooks, inline worker)"
open_url "https://dashboard.render.com/web/new"
step "Connect this GitHub repo, branch main."
step "Name: ${APP_SERVICE}  (must match — it IS the hostname) ·"
step "Region: ${RENDER_REGION:-same as the database} · Instance: FREE."
step "Build command:"
say  "    pip install uv && uv sync --frozen"
step "Start command (single line; NEVER add --workers — the inline worker"
step "must run exactly once):"
say  "    uv run alembic upgrade head && uv run uvicorn becca.web.app:create_app --factory --host 0.0.0.0 --port \$PORT --proxy-headers --forwarded-allow-ips '*'"
step "Environment: 'Add from .env' -> paste the ENTIRE contents of .env.demo,"
step "then add ONE extra variable BY HAND on this service only:"
say  "    INLINE_WORKER=true"
note "That flag runs the dispatcher/housekeeper inside this web process —"
note "the free tier has no worker service type. Console must NOT set it."
step "Create the service."
pause "Press Enter once the first deploy is building..."
note "First build takes a few minutes (Python 3.14 + uv sync)."
say ""
warn "Render may have RENAMED the service (it uses the repo name, or adds a"
warn "suffix when a name is taken). The hostname is load-bearing: the demo"
warn "sign-in redirects to CLIENT_HOST and Telnyx calls back PUBLIC_WEBHOOK_BASE."
step "Copy the service URL shown at the top of its Render page."
ask APP_URL_ACTUAL "Paste the app service URL (https://....onrender.com):"
APP_HOST_ACTUAL="${APP_URL_ACTUAL#https://}"; APP_HOST_ACTUAL="${APP_HOST_ACTUAL#http://}"; APP_HOST_ACTUAL="${APP_HOST_ACTUAL%%/*}"
if [[ -n "$APP_HOST_ACTUAL" && "$APP_HOST_ACTUAL" != "${APP_SERVICE}.onrender.com" ]]; then
  APP_SERVICE="${APP_HOST_ACTUAL%.onrender.com}"
  write_env APP_SERVICE "$APP_SERVICE"
  write_env CLIENT_HOST "$APP_HOST_ACTUAL"
  write_env PUBLIC_WEBHOOK_BASE "https://${APP_HOST_ACTUAL}"
  warn "Hostname differed. In Render, on THIS service's Environment, set:"
  say  "    CLIENT_HOST=${APP_HOST_ACTUAL}          (bare hostname — no https://, no slash)"
  say  "    PUBLIC_WEBHOOK_BASE=https://${APP_HOST_ACTUAL}"
  say  "(the console service, next, must get the same two values)"
  pause "Press Enter once saved (it auto-redeploys)..."
else
  say "hostname matches — nothing to change."
fi

# ── Stage 8 ────────────────────────────────────────────────────────────────
stage "Render — the CONSOLE web service"
open_url "https://dashboard.render.com/web/new"
step "Same repo, branch main · Name: ${CONSOLE_SERVICE} ·"
step "Region: ${RENDER_REGION:-same as the database} · Instance: FREE."
step "Build command:  pip install uv && uv sync --frozen"
step "Start command (NO alembic prefix here — two boots must never race a"
step "migration; the app service owns it):"
say  "    uv run uvicorn becca.web.app:create_app --factory --host 0.0.0.0 --port \$PORT --proxy-headers --forwarded-allow-ips '*'"
step "Environment: 'Add from .env' -> paste the same .env.demo. Do NOT add"
step "INLINE_WORKER here."
step "Create the service."
note "This service is allowed to sleep (staff-only; ~60s cold start when you"
note "open it). Only the app service gets a keep-warm pinger — two always-on"
note "free services would blow the workspace's shared 750 h/month."
pause "Press Enter once the console deploy is building..."
step "Copy the console service URL shown at the top of its Render page."
ask CONSOLE_URL_ACTUAL "Paste the console service URL (https://....onrender.com):"
CONSOLE_HOST_ACTUAL="${CONSOLE_URL_ACTUAL#https://}"; CONSOLE_HOST_ACTUAL="${CONSOLE_HOST_ACTUAL#http://}"; CONSOLE_HOST_ACTUAL="${CONSOLE_HOST_ACTUAL%%/*}"
if [[ -n "$CONSOLE_HOST_ACTUAL" && "$CONSOLE_HOST_ACTUAL" != "${CONSOLE_SERVICE}.onrender.com" ]]; then
  CONSOLE_SERVICE="${CONSOLE_HOST_ACTUAL%.onrender.com}"
  write_env CONSOLE_SERVICE "$CONSOLE_SERVICE"
  write_env CONSOLE_HOST "$CONSOLE_HOST_ACTUAL"
  warn "Hostname differed. On BOTH services' Environment in Render, set:"
  say  "    CONSOLE_HOST=${CONSOLE_HOST_ACTUAL}       (bare hostname)"
  pause "Press Enter once saved on both..."
fi
warn "If the APP hostname changed in the previous stage, set the same two"
warn "values (CLIENT_HOST, PUBLIC_WEBHOOK_BASE) on THIS service's env too."
pause "Press Enter to continue..."

# ── Stage 9 ────────────────────────────────────────────────────────────────
stage "Seed the demo account"
say "Creates the 'Becca Demo' client account + ${DEMO_USER_EMAIL} and funds"
say "the wallet. Idempotent — RE-RUN THIS EXACT COMMAND any time mid-demo to"
say "refill the wallet:"
say ""
say "    DATABASE_URL=<External URL> uv run python scripts/seed_demo.py \\"
say "        --email ${DEMO_USER_EMAIL} --credit 20"
say ""
ask DEMO_CREDIT "Wallet target in USD [20]:"
DEMO_CREDIT=${DEMO_CREDIT:-20}
if confirm "Run the seed now?"; then
  if DATABASE_URL="$EXTERNAL_URL_VALUE" uv run python scripts/seed_demo.py --email "$DEMO_USER_EMAIL" --credit "$DEMO_CREDIT"; then
    say "seeded."
  else
    warn "seed failed — check the External URL and rerun this wizard."
    SKIPPED+=("scripts/seed_demo.py against the demo database")
  fi
else
  SKIPPED+=("scripts/seed_demo.py against the demo database")
fi

# ── Stage 10 ───────────────────────────────────────────────────────────────
stage "Verify the deploy"
say "Checking what must be true before anyone scans anything:"
_check() { # label url expect_code
  local label="$1" url="$2" expect="$3" code
  code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 90 "$url" || echo "000")
  if [[ "$code" == "$expect" ]]; then
    printf '  %s✓%s %s (%s)\n' "$GREEN" "$RESET" "$label" "$code"
  else
    printf '  %s✗ %s — got %s, expected %s%s\n' "$RED" "$label" "$code" "$expect" "$RESET"
    SKIPPED+=("verify: $label returned $code (expected $expect)")
  fi
}
note "(a sleeping service takes ~60s on its first hit — that's the free tier)"
_check "app plane sign-in page"       "https://${APP_SERVICE}.onrender.com/auth/signin"          200
_check "console plane sign-in page"   "https://${CONSOLE_SERVICE}.onrender.com/auth/signin"      200
_check "dev-login backdoor ABSENT"    "https://${APP_SERVICE}.onrender.com/auth/dev?email=x"     404
_check "demo route refuses bad code"  "https://${APP_SERVICE}.onrender.com/auth/demo?code=nope"  303
_check "demo route absent on console" "https://${CONSOLE_SERVICE}.onrender.com/auth/demo?code=x" 404
_check "webhook endpoint reachable"   "https://${APP_SERVICE}.onrender.com/webhooks/telnyx"      405
pause

# ── Stage 11 ───────────────────────────────────────────────────────────────
stage "Build the three example agents — by hand, through the real product"
DEMO_URL="https://${APP_SERVICE}.onrender.com/auth/demo?code=${DEMO_CODE_VALUE}"
say "Sign in AS the demo user and build each agent: Describe -> (Revise if"
say "needed) -> Voice -> Test. Place one real test call to YOUR OWN phone per"
say "agent so each arrives demo-day with a green 'tested' state."
open_url "$DEMO_URL"
say ""
say "Three briefs to paste into Describe — distinct on purpose (they also"
say "spread concurrent visitors across agents):"
say ""
say "  1) Solar leads:"
note "     Call homeowners in Lagos who asked for a solar quote on our website."
note "     Confirm they're still interested, ask what they currently spend on"
note "     power monthly (generator + PHCN), whether their roof is concrete or"
note "     sheet, and when they'd want installation. Friendly, brief, no hard sell."
say "  2) Property viewings:"
note "     Call people who enquired about a 3-bedroom terrace in Lekki Phase 1."
note "     Confirm they'll attend Saturday's inspection at 10am, ask their"
note "     budget range and whether they're paying cash or on a plan. Offer to"
note "     reschedule if Saturday fails; capture the better day."
say "  3) Event RSVPs:"
note "     Call registered guests for the Lagos SME Growth Summit. Confirm"
note "     attendance, ask their dietary preference and whether they're"
note "     bringing a plus-one. Warm and quick — under two minutes."
pause "Press Enter when all three agents exist and each has a passing test call..."

# ── Stage 12 ───────────────────────────────────────────────────────────────
stage "Keep-warm pinger + the QR code"
say "Free services sleep after 15 idle minutes (~60s wake). A visitor's scan"
say "or a Telnyx webhook must never eat that — so ping the APP service only."
open_url "https://uptimerobot.com"
step "Create a free account -> Add New Monitor -> HTTP(s):"
say  "    URL:      https://${APP_SERVICE}.onrender.com/auth/signin"
say  "    Interval: 5 minutes"
step "(Delete this monitor after the event — it's what spends instance hours.)"
pause "Press Enter once the monitor is up..."
say ""
say "The QR code IS the sign-in. It must encode EXACTLY this URL (the app"
say "host — the console host would land visitors signed out):"
say ""
say "    ${DEMO_URL}"
say ""
if command -v qrencode >/dev/null 2>&1; then
  qrencode -t ANSIUTF8 "$DEMO_URL" || true
  say "(also saving demo-qr.png next to this script)"
  qrencode -o scripts/demo-qr.png -s 10 "$DEMO_URL" || true
else
  step "qrencode isn't installed — generate the QR at a generator you trust"
  step "(the URL contains the access code) and print it big for the pitch."
fi
note "Leak plan: if the code escapes early, change DEMO_ACCESS_CODE on the"
note "app service's env in Render — it auto-redeploys and old QRs die."

# ── Stage 13 ───────────────────────────────────────────────────────────────
stage "Demo-day smoke test + the day after"
say "The full visitor journey, on your own phone, before you pitch:"
step "Scan the QR -> you land signed in on the Becca Demo overview."
step "Open an example agent -> Test -> enter YOUR number -> phone rings ->"
step "have the conversation -> transcript + extracted answers appear."
step "Open Launch: the button is disabled with a 'blocking' pill — intended."
step "(That's the pre-flight safety gate; visitors can see it, never fire it.)"
step "Billing: the wallet visibly debited for your test call."
say ""
say "The day after the demo:"
step "Blank DEMO_ACCESS_CODE on the app service env (route vanishes on the"
step "auto-redeploy); rotate SESSION_SECRET to kill any 14-day cookies."
step "Delete the UptimeRobot monitor."
step "pg_dump anything you want to keep — the free DB expires 30 days after"
step "creation."
step "Delete the two services + database in Render when done."
pause "Press Enter to finish..."

finish
say "Re-run any time: bash scripts/demo-wizard.sh — it remembers .env.demo."
say "Mid-demo wallet refill:"
say "  DATABASE_URL=<External URL> uv run python scripts/seed_demo.py --email ${DEMO_USER_EMAIL} --credit 40"
