#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10
ENV_FILE=".env.staging"

banner "Becca — staging deploy (real domains, staging rails)"

# ── Stage 1 ────────────────────────────────────────────────────────────────
stage "Preflight — fixed values and a fresh session secret"
say "Everything this wizard collects lands in .env.staging. At the Render"
say "stages you paste that file straight into Render's env editor."
if ! grep -q '^\.env\.staging$' .gitignore 2>/dev/null; then
  printf '.env.staging\n' >> .gitignore
  say "added .env.staging to .gitignore (it will hold real secrets)"
fi
SESSION_SECRET_VALUE=$(openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')
write_env ENVIRONMENT "staging"
write_env SESSION_SECRET "$SESSION_SECRET_VALUE"
write_env CLIENT_HOST "app.becca.live"
write_env CONSOLE_HOST "console.becca.live"
write_env COOKIE_DOMAIN "becca.live"
write_env PUBLIC_WEBHOOK_BASE "https://app.becca.live"
write_env TELNYX_MODE "real"
write_env ASSISTANT_CONVERSATION_MODEL "anthropic/claude-haiku-4-5"
write_env ASSISTANT_VOICE "Telnyx.Ultra.81d6df1d-6175-4f24-9641-76d14b6d67cc"
write_env PYTHON_VERSION "3.14.0"
note "ENVIRONMENT=staging keeps the SD-13 dial allowlist ENFORCED: this deploy"
note "can only ever dial the numbers you list next. Go-live later is flipping"
note "this one value to 'production' in Render."
[[ -f .env ]] && note "suggested values below are read from your dev .env where present."
DEV_ALLOWLIST=$(grep -E '^DIAL_ALLOWLIST=' .env 2>/dev/null | cut -d= -f2- || true)
[[ -n "$DEV_ALLOWLIST" ]] && say "dev allowlist: $DEV_ALLOWLIST"
ask DIAL_ALLOWLIST "Comma-separated E.164 numbers staging may dial (your own phones):"
write_env DIAL_ALLOWLIST "$DIAL_ALLOWLIST"
DEV_FROM=$(grep -E '^TELNYX_FROM_NUMBER=' .env 2>/dev/null | cut -d= -f2- || true)
[[ -n "$DEV_FROM" ]] && say "dev from-number: $DEV_FROM"
ask TELNYX_FROM_NUMBER "Caller ID for test calls (the 020 Lagos number works):"
write_env TELNYX_FROM_NUMBER "$TELNYX_FROM_NUMBER"
ask BECCA_STAFF_EMAILS "Comma-separated staff Google emails (seeded on first sign-in):"
write_env BECCA_STAFF_EMAILS "$BECCA_STAFF_EMAILS"
ask BANK_TRANSFER_DETAILS "Bank transfer details for client invoices (blank = contact fallback):"
write_env BANK_TRANSFER_DETAILS "$BANK_TRANSFER_DETAILS"

# ── Stage 2 ────────────────────────────────────────────────────────────────
stage "Google OAuth client"
say "Both hostnames get an authorized redirect URI now — no rework at go-live."
open_url "https://console.cloud.google.com/apis/credentials"
step "Pick (or create) a project for Becca."
step "If asked, configure the OAuth consent screen first: External, app name"
step "'Becca', your support email; scopes: only 'openid' and 'email'; add your"
step "own Google accounts as test users while the app is unverified."
step "Then: Create credentials -> OAuth client ID -> type 'Web application',"
step "name 'becca-staging'."
step "Under 'Authorized redirect URIs' add BOTH, exactly:"
say  "    https://app.becca.live/auth/callback"
say  "    https://console.becca.live/auth/callback"
step "Create, then copy the Client ID and Client secret."
ask GOOGLE_CLIENT_ID "Paste the Client ID:"
ask_secret GOOGLE_CLIENT_SECRET "Paste the Client secret:"
write_env GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
write_env GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"
note "With these set, the /auth/dev backdoor does not exist on this deploy —"
note "the code only builds it when env=dev AND no Google credentials."

# ── Stage 3 ────────────────────────────────────────────────────────────────
stage "Telnyx — a staging API key of its own"
say "Per-env keys were your deploy-time hygiene plan: a leaked staging key"
say "can be revoked without touching dev."
open_url "https://portal.telnyx.com/#/app/api-keys"
step "Create an API key named 'becca-staging' and copy it."
ask_secret TELNYX_API_KEY "Paste the Telnyx API key:"
write_env TELNYX_API_KEY "$TELNYX_API_KEY"
step "From Account Settings -> Keys & Credentials, copy the account PUBLIC key"
step "(used to verify webhook signatures — it is not secret)."
ask TELNYX_PUBLIC_KEY "Paste the Telnyx public key:"
write_env TELNYX_PUBLIC_KEY "$TELNYX_PUBLIC_KEY"

# ── Stage 4 ────────────────────────────────────────────────────────────────
stage "Anthropic — a staging API key of its own"
open_url "https://console.anthropic.com/settings/keys"
step "Create a key named 'becca-staging' and copy it."
ask_secret ANTHROPIC_API_KEY "Paste the Anthropic API key:"
write_env ANTHROPIC_API_KEY "$ANTHROPIC_API_KEY"

# ── Stage 5 ────────────────────────────────────────────────────────────────
stage "Render — managed Postgres"
open_url "https://dashboard.render.com/new/database"
step "Name: becca-staging-db · Region: Frankfurt (EU Central) · pick the"
step "cheapest NON-free paid tier (free DBs expire after 30 days)."
step "Create, wait for it to become available, then copy the"
step "'Internal Database URL' (starts postgresql://...)."
ask RAW_DATABASE_URL "Paste the Internal Database URL:"
DATABASE_URL_VALUE="${RAW_DATABASE_URL/postgresql:\/\//postgresql+asyncpg:\/\/}"
DATABASE_URL_VALUE="${DATABASE_URL_VALUE/postgres:\/\//postgresql+asyncpg:\/\/}"
write_env DATABASE_URL "$DATABASE_URL_VALUE"
note "rewrote the scheme to postgresql+asyncpg:// — the app's driver needs it."
note "RLS note: Render's DB user is not a superuser and every policy is FORCE"
note "row security, so migrations run and tenant isolation stays enforced."

# ── Stage 6 ────────────────────────────────────────────────────────────────
stage "Render — the web service"
open_url "https://dashboard.render.com/web/new"
step "Connect the GitHub repo (becca-org/BeccaVoiceCallQualification), branch main."
step "Name: becca-web · Region: Frankfurt · Instance: Starter (NEVER Free —"
step "free sleeps after 15 min and silently drops Telnyx webhooks)."
step "Build command:"
say  "    pip install uv && uv sync --frozen"
step "Start command (--proxy-headers is load-bearing: without it OAuth"
step "generates http:// redirect URIs behind Render's proxy and Google refuses):"
say  "    uv run uvicorn becca.web.app:create_app --factory --host 0.0.0.0 --port \$PORT --proxy-headers --forwarded-allow-ips '*'"
step "Pre-deploy command (runs migrations before each deploy goes live):"
say  "    uv run alembic upgrade head"
step "Environment: choose 'Add from .env' and paste the ENTIRE contents of"
step ".env.staging (this file). Then create the service."
pause "Press Enter once the first deploy is building..."
note "The first deploy may take a few minutes (Python 3.14 + uv sync)."

# ── Stage 7 ────────────────────────────────────────────────────────────────
stage "Render — the dispatcher worker"
open_url "https://dashboard.render.com/worker/new"
step "Same repo, branch main · Name: becca-worker · Region: Frankfurt ·"
step "Instance: Starter."
step "Build command:  pip install uv && uv sync --frozen"
step "Start command:  uv run python -m becca.worker"
step "Environment: 'Add from .env' -> paste the same .env.staging contents."
step "Create the service."
pause "Press Enter once the worker deploy is building..."

# ── Stage 8 ────────────────────────────────────────────────────────────────
stage "Custom domains and DNS"
say "Two hostnames, one web service — the app routes by Host header."
open_url "https://dashboard.render.com"
step "Open becca-web -> Settings -> Custom Domains -> add BOTH:"
say  "    app.becca.live"
say  "    console.becca.live"
step "Render shows a CNAME target like becca-web-xxxx.onrender.com."
ask RENDER_CNAME_TARGET "Paste that CNAME target:"
step "At your DNS registrar for becca.live, create two CNAME records:"
say  "    app      ->  $RENDER_CNAME_TARGET"
say  "    console  ->  $RENDER_CNAME_TARGET"
pause "Press Enter once both records are saved..."
say "Waiting for DNS to answer (can take a few minutes)..."
for host in app.becca.live console.becca.live; do
  until nslookup "$host" >/dev/null 2>&1; do
    printf '  %s.%s' "$DIM" "$RESET"; sleep 15
  done
  printf '\n'; say "found: $host resolves"
done
note "Render now issues Let's Encrypt certificates for both — usually under"
note "a minute after DNS resolves. The next stage verifies over https."

# ── Stage 9 ────────────────────────────────────────────────────────────────
stage "Verify the deploy"
say "Checking the things that must be true before anyone signs in:"
_check() { # label url expect_code
  local label="$1" url="$2" expect="$3" code
  code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 30 "$url" || echo "000")
  if [[ "$code" == "$expect" ]]; then
    printf '  %s✓%s %s (%s)\n' "$GREEN" "$RESET" "$label" "$code"
  else
    printf '  %s✗ %s — got %s, expected %s%s\n' "$RED" "$label" "$code" "$expect" "$RESET"
    SKIPPED+=("verify: $label returned $code (expected $expect)")
  fi
}
_check "client plane sign-in page"  "https://app.becca.live/auth/signin"      200
_check "console plane sign-in page" "https://console.becca.live/auth/signin"  200
_check "dev-login backdoor ABSENT"  "https://app.becca.live/auth/dev?email=x" 404
_check "webhook endpoint reachable" "https://app.becca.live/webhooks/telnyx"  405
note "webhooks answer on any hostname; 405 means the route exists and only"
note "rejects GET, which is correct."
pause

# ── Stage 10 ───────────────────────────────────────────────────────────────
stage "First sign-in and console smoke test"
open_url "https://console.becca.live"
step "Sign in with Google using a staff email you listed in stage 1."
step "The console landing should render: balance, client list (empty),"
step "burn-rate panel. This is also the first LIVE exercise of the five"
step "console gateway endpoints (balance, numbers, orders, profiles) on"
step "this account key — if a panel shows 'unavailable', tell Claude."
step "Then: Clients -> New client to create the client account, add its"
step "owner's Google email, and the client plane at app.becca.live works."
note "The staging database starts EMPTY — dev agents/results don't carry over."
pause "Press Enter when you've signed in and the console renders..."

finish
say "Go-live later: change ENVIRONMENT to 'production' on both Render services"
say "(web + worker). That single flip disables the dial allowlist (SD-13) and"
say "enforces the real SESSION_SECRET guard. Nothing else changes."
